### ISSUE TITLE
Official documentation is offline

### ISSUE THREAD

**Issue by lpignotti** [Hackdoor-io/cezanne#12]
Hi all,

when I click on official documentation link 
![image](https://user-images.githubusercontent.com/26708387/103177067-63f15300-4877-11eb-9611-6723558116ad.png)

I receive the following error
![image](https://user-images.githubusercontent.com/26708387/103177106-c5b1bd00-4877-11eb-9f8e-5bec89228f32.png)

**Comment by micheleriva** [comment]
Hey @lpignotti! Thank you so much for letting us know. You can reach the documentation here: https://hackdoor-io.github.io/cezanne we will be updating the Readme ASAP 😃 

By the way, while Cézanne works great, I'd suggest you take a look at Gauguin: https://github.com/micheleriva/gauguin.
In Hackdoor we moved from Cézanne to Gauguin because of its better performances (written in Go and compiled to native code) and we will keep it more updated.

Cheers!
